//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TortugaSmirnova.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Composition
    {
        public int DishID { get; set; }
        public string DishTitle { get; set; }
        public string Composition { get; set; }
    }
}
